#!/bin/sh

# https://ops.tips/blog/using-network-namespaces-and-bridge-to-isolate-servers/

ip link add name br1 type bridge
ip link set br1 up
ip addr add 192.168.1.10/24 brd + dev br1
iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE
sysctl -w net.ipv4.ip_forward=1

configure_namespace() {
  name=$1; shift
  ip=$1; shift

  namespace="${name}"
  veth="veth-${name}"
  br_veth="br-veth-${name}"

  ip netns add "${namespace}"
  ip link add "${veth}" type veth peer name "${br_veth}"
  ip link set "${veth}" netns "${namespace}"

  ip netns exec "${namespace}" ip addr add "${ip}/24" dev "${veth}"

  ip link set "${br_veth}" up
  ip netns exec "${namespace}" ip link set "${veth}" up
  ip link set "${br_veth}" master br1
  ip netns exec "${namespace}" ip route add default via 192.168.1.10

  echo "${ip} ${name}.spin" >> /etc/hosts
}

configure_namespace shopify 192.168.1.11
configure_namespace web 192.168.1.12
